apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  steps:
    - name: cleanup
      image: alpine
      script: |
        echo "ðŸ§¹ Running cleanup task..."
        rm -rf /workspace/output/tmp || true

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test-task
spec:
  steps:
    - name: run-nose-tests
      image: python:3.10
      script: |
        pip install nose
        nosetests

